/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryNewRouteImport } from './routes/memory.new'
import { Route as MemoryIdRouteImport } from './routes/memory.$id'
import { Route as MemoryIdEditRouteImport } from './routes/memory.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryNewRoute = MemoryNewRouteImport.update({
  id: '/memory/new',
  path: '/memory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIdRoute = MemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIdEditRoute = MemoryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MemoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/memory/$id': typeof MemoryIdRouteWithChildren
  '/memory/new': typeof MemoryNewRoute
  '/memory/$id/edit': typeof MemoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/memory/$id': typeof MemoryIdRouteWithChildren
  '/memory/new': typeof MemoryNewRoute
  '/memory/$id/edit': typeof MemoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quotes': typeof QuotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/memory/$id': typeof MemoryIdRouteWithChildren
  '/memory/new': typeof MemoryNewRoute
  '/memory/$id/edit': typeof MemoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/forgot'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/reset-password'
    | '/signup'
    | '/memory/$id'
    | '/memory/new'
    | '/memory/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/forgot'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/reset-password'
    | '/signup'
    | '/memory/$id'
    | '/memory/new'
    | '/memory/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/forgot'
    | '/login'
    | '/profile'
    | '/quotes'
    | '/reset-password'
    | '/signup'
    | '/memory/$id'
    | '/memory/new'
    | '/memory/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuotesRoute: typeof QuotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  MemoryIdRoute: typeof MemoryIdRouteWithChildren
  MemoryNewRoute: typeof MemoryNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/new': {
      id: '/memory/new'
      path: '/memory/new'
      fullPath: '/memory/new'
      preLoaderRoute: typeof MemoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$id': {
      id: '/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof MemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$id/edit': {
      id: '/memory/$id/edit'
      path: '/edit'
      fullPath: '/memory/$id/edit'
      preLoaderRoute: typeof MemoryIdEditRouteImport
      parentRoute: typeof MemoryIdRoute
    }
  }
}

interface MemoryIdRouteChildren {
  MemoryIdEditRoute: typeof MemoryIdEditRoute
}

const MemoryIdRouteChildren: MemoryIdRouteChildren = {
  MemoryIdEditRoute: MemoryIdEditRoute,
}

const MemoryIdRouteWithChildren = MemoryIdRoute._addFileChildren(
  MemoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuotesRoute: QuotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  MemoryIdRoute: MemoryIdRouteWithChildren,
  MemoryNewRoute: MemoryNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
